apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  selector:
    app: employee
  type: ClusterIP
  ports:
    - port: 80          # ðŸ‘ˆ STANDARD SERVICE PORT
      targetPort: 8080
      protocol: TCP
